# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= APP_CONFIG[Rails.env]["SECRET_TOKEN"] %>

test:
  secret_key_base: <%= APP_CONFIG[Rails.env]["SECRET_TOKEN"] %>

production:
  secret_key_base: <%= APP_CONFIG[Rails.env]["SECRET_TOKEN"] %>

# I can't believe rails ended up doing it like this. You finally added the big thing I wanted it but you don't even do it right. Fucking rails.